---
kuber:
  hosts:
    manager-1:
      ansible_host: MAN1
      ansible_ssh_user: ansible
    worker-1:
      ansible_host: WOR1
      ansible_ssh_user: ansible

managers:
  hosts:
    # Only include the manager nodes
    manager-1:
      ansible_host: MAN1
      ansible_ssh_user: ansible

workers:
  hosts:
    # Only include the worker nodes
    worker-1:
      ansible_host: WOR1
      ansible_ssh_user: ansible
