---

stages:
  - ansible_test
  - lint_test
  - prepare_system
  - prepare_worker

image: leshevi1/lin-ansible:01

variables:
  ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  ANSIBLE_ROLES_PATH: roles
  ANSIBLE_INVENTORY: inventories
  ANSIBLE_REMOTE_TMP: /tmp
  ANSIBLE_FORCE_COLOR: 'true'
  ANSIBLE_STARATEGY: linear
  ANSIBLE_PIPELINING: 1
  ANSIBLE_TRANSPORT: ssh
  ANSIBLE_BECOME_EXE: sudo
  ANSIBLE_BECOME_METHOD: 'su' # нужно если поднимаются права через su с вводом пароля от root
  ANSIBLE_BECOME_USER: root
  ANSIBLE_BECOME_ASKPASS: 'False'
  ANSIBLE_FORCE_HANDLER: 'True'
  ANSIBLE_STDOUT_CALLBACK: yaml
  ANSIBLE_ASK_PASS: 'False'
  ANSIBLE_NOCOWS: 1
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  ANSIBLE_BECOME_EXE: 'sudo -p "Password: " su -'
  DEPRECATION_WARNINGS: 'false'
  ANSIBLE_TIMEOUT: 30

.job_inj:
  before_script:
    - rm .gitlab-ci.yml README.md
    - eval $(ssh-agent -s)
    - echo "$SSH_ROOT_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - |+
      sed -i "s!MAN1!${MAN1}!" inventories/hosts.yml
      sed -i "s!WOR1!${WOR1}!" inventories/hosts.yml
      sed -i "s!WOR2!${WOR2}!" inventories/hosts.yml
    - cat inventories/hosts.yml

ansible_test:
  stage: ansible_test
  when: manual
  only:
    refs:
      - main
  tags:
    - Docker
  script:
    - ansible --version
    - ansible-lint --version

ansible_lint_test:
  stage: lint_test
  when: manual
  tags:
    - Docker
  only:
    refs:
      - main
    changes:
      - "inventories/**/*"
      - "playbooks/**/*"
      - "roles/**/*"
      - ".gitlab-ci.yml"
  extends: .job_inj
  script:
    - ansible-lint -q --offline

ansible_prepare_system:
  stage: prepare_system
  tags:
    - Docker
  when: manual
  only:
    refs:
      - main
    changes:
      - "inventories/**/*"
      - "playbooks/**/*"
      - "roles/**/*"
      - ".gitlab-ci.yml"
  needs:
    - ansible_lint_test
  extends: .job_inj
  script:
    - ansible-playbook playbooks/site.yml

ansible_prepare_worker:
  stage: prepare_worker
  tags:
    - Docker
  when: manual
  only:
    refs:
      - main
    changes:
      - "inventories/**/*"
      - "playbooks/**/*"
      - "roles/**/*"
      - ".gitlab-ci.yml"
  needs:
    - ansible_lint_test
  extends: .job_inj
  script:
    - ansible-playbook playbooks/site1.yml
